src/Entity/Project/Category.php
<?php
namespace App\Entity\Project;

use App\Entity\Project\Lists\CategoryList;
use App\Traits\Entity\Hydrate;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Category
 *
 * @ORM\Entity
 * @ORM\Table(name="project_category")
 */
class Category{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=75)
     *
     * @Assert\NotBlank(message="Veuillez renseigner un titre")
     * @Assert\Type(
     *     type="string",
     *     message="Le titre doit être une chaine de caractères"
     * )
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="slug_name", type="string", length=255)
     */
    protected $slugName;

    /**
     * @var string
     *
     * @ORM\Column(name="summary", type="text")
     *
     * @Assert\NotBlank(message="Veuillez renseigner un résumé")
     * @Assert\Type(
     *     type="string",
     *     message="Le résumé doit être une chaine de caractères"
     * )
     */
    private $summary;

    /**
     * @var mixed
     *
     * @ORM\OneToMany(
     *     targetEntity="\App\Entity\Project\Lists\CategoryList",
     *     mappedBy="category",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     * @Orm\OrderBy({"position" = "ASC"})
     *
     * @Assert\Valid
     * @Assert\Count(
     *      min = 1,
     *      minMessage = "Veuillez fournir au moins une compétence"
     * )
     */
    private $skillListItems;

    /**
     * Category's projects
     *
     * @var mixed
     *
     * @ORM\OneToMany(
     *     targetEntity="\App\Entity\Project\Project",
     *     mappedBy="category"
     * )
     * @ORM\OrderBy({"endDate" = "DESC"})
     */
    private $projects;

    // Traits
    use Hydrate;

    /**
     * Get id
     *
     * @return int
     */
    public function getId(){
        return $this->id;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get summary
     *
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Set summary
     *
     * @param string $summary
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
    }

    /**
     * @return mixed
     */
    public function getDistantMedias()
    {
        return $this->distantMedias;
    }

    /**
     * @return mixed
     */
    public function getProjects()
    {
        return $this->projects;
    }

    /**
     * @param mixed $projects
     */
    public function setProjects($projects)
    {
        $this->projects = $projects;
    }

    /**
     * @return string
     */
    public function getSlugName(): string
    {
        return $this->slugName;
    }

    /**
     * @param string $slugName
     */
    public function setSlugName(string $slugName)
    {
        $this->slugName = $slugName;
    }

    /**
     * @return mixed
     */
    public function getSkillListItems()
    {
        return $this->skillListItems;
    }

    public function setSkillListItems($skillListItems)
    {
        // Avoid existant skillListItems duplication
        $this->skillListItems->clear();

        // Loop and assign Entities to this Book
        foreach($skillListItems as $skill){
            if($skill instanceof CategoryList){
                $this->addSkillListItem($skill);
            }
        }
    }

    public function addSkillListItem(CategoryList $skill) {
        // Add BookHasMedia to array
        $this->skillListItems->add($skill);
        //Set this to bookHasMedia
        $skill->setCategory($this);
    }

}

src/Entity/Project/Project.php
<?php
namespace App\Entity\Project;

use App\Entity\Project\Lists\ProjectList;
use App\Entity\Sonata\CoverImage;
use App\Traits\Entity\Hydrate;
use App\Entity\Sonata\ProjectHasMedia;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Project
 *
 * @ORM\Entity("App\Repository\Project\ProjectRepository")
 * @ORM\Table(name="project_project")
 * @ORM\EntityListeners({"App\EventListener\Project"})
 */
class Project{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=75)
     *
     * @Assert\NotBlank(message="Veuillez renseigner un titre")
     * @Assert\Type(
     *     type="string",
     *     message="Le nom doit être une chaine de caractères"
     * )
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="slug_name", type="string", length=255)
     */
    protected $slugName;

    /**
     * Date of project initialisation
     *
     * @var \DateTime
     *
     * @ORM\Column(name="init_date", type="date")
     *
     * @Assert\NotNull(message="Veuillez renseigner une date de début")
     */
    private $initDate;

    /**
     * Date of project ending
     *
     * @var \DateTime
     *
     * @ORM\Column(name="end_date", type="date")
     *
     * @Assert\NotNull(message="Veuillez renseigner une date de fin")
     */
    private $endDate;

    /**
     * @var string
     *
     * @ORM\Column(name="summary", type="text")
     *
     * @Assert\NotBlank(message="Veuillez renseigner un résumé")
     * @Assert\Type(
     *     type="string",
     *     message="Le résumé doit être une chaine de caractères"
     * )
     */
    private $summary;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     *
     * @Assert\NotBlank(message="Veuillez renseigner un contenu")
     * @Assert\Type(
     *     type="string",
     *     message="Le contenu doit être une chaine de caractères"
     * )
     */
    private $content;

    /**
     * @var string
     *
     * @ORM\Column(name="raw_content", type="text")
     *
     * @Assert\NotBlank(message="Veuillez renseigner un contenu")
     */
    private $rawContent;

    /**
     * @var int
     *
     * @ORM\Column(name="contributors_nbre", type="integer")
     *
     * @Assert\NotNull(message="Veuillez renseigner un nombre de collaborateurs")
     * @Assert\Type(
     *     type="int",
     *     message="Le nombre de collaborateurs doit être un entier"
     * )
     */
    private $contributorsNbre;

    /**
     * @var string
     *
     * @ORM\Column(name="hc_type", type="string")
     *
     * @Assert\NotBlank(message="Veuillez renseigner un type de concept")
     * @Assert\Type(
     *     type="string",
     *     message="Le type du concept doit être une chaine de caractères"
     * )
     */
    private $highConceptType;

    /**
     * @var string
     *
     * @ORM\Column(name="hc_gender", type="string")
     *
     * @Assert\NotBlank(message="Veuillez renseigner un genre de concept")
     * @Assert\Type(
     *     type="string",
     *     message="Le genre du concept doit être une chaine de caractères"
     * )
     */
    private $highConceptGender;

    /**
     * @var string
     *
     * @ORM\Column(name="hc_target", type="string")
     *
     * @Assert\NotBlank(message="Veuillez renseigner une cible pour le concept")
     * @Assert\Type(
     *     type="string",
     *     message="La cible du concept doit être une chaine de caractères"
     * )
     */
    private $highConceptTarget;

    /**
     * @var mixed
     *
     * @ORM\OneToMany(
     *     targetEntity="\App\Entity\Project\Lists\ProjectList",
     *     mappedBy="project",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     * @Orm\OrderBy({"position" = "ASC"})
     *
     * @Assert\Valid
     * @Assert\Count(
     *      min = 1,
     *      minMessage = "Veuillez fournir au moins une compétence"
     * )
     */
    private $skillListItems;

    /**
     * Category of project
     *
     * @var Category
     *
     * @ORM\ManyToOne(
     *     targetEntity="\App\Entity\Project\Category",
     *     inversedBy="projects"
     * )
     *
     * @Assert\NotNull(message="La catégorie est obligatoire")
     * @Assert\Type(
     *     type="object",
     *     message="La catégorie doit être un objet de type Category"
     * )
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @var CoverImage
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Sonata\CoverImage", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @Assert\NotNull(message="L'image de couverture est obligatoire")
     * @Assert\Type(
     *     type="object",
     *     message="L'image de couverture doit être un objet CoverImage"
     * )
     */
    private $coverImage;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Sonata\ProjectHasMedia",
     *     mappedBy="project",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     * @Orm\OrderBy({"position" = "ASC"})
     *
     * @Assert\Count(
     *      min = 1,
     *      minMessage = "Veuillez fournir au moins un élément de gallerie"
     * )
     */
    private $projectHasMedias;

    /**
     * @var EventDispatcher
     */
    private $contentFormatter;

    // Traits
    use Hydrate;

    public function __construct()
    {
        $this->projectHasMedias = new ArrayCollection();
        $this->skillListItems = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId(){
        return $this->id;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName(string $name)
    {
        $this->name = $name;
    }

    /**
     * Get summary
     *
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Set summary
     *
     * @param string $summary
     */
    public function setSummary(string $summary)
    {
        $this->summary = $summary;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory(Category $category)
    {
        $this->category = $category;
    }

    /**
     * @return \DateTime
     */
    public function getInitDate()
    {
        return $this->initDate;
    }

    private function stringToDateTime(string $date)
    {
        return new \DateTime($date);
    }

    /**
     * @param \DateTime|string $initDate
     */
    public function setInitDate($initDate)
    {
        if(is_string($initDate)) $initDate = $this->stringToDateTime($initDate);

        $this->initDate = $initDate;
    }

    /**
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * @param \DateTime|string $endDate
     */
    public function setEndDate($endDate)
    {
        if(is_string($endDate)) $endDate = $this->stringToDateTime($endDate);

        $this->endDate = $endDate;
    }

    public function getDuration()
    {
        return $this->getInitDate()
            ->diff(
                $this->getEndDate(),
                true
            )
            ->format('%a jours')
        ;
    }

    public function getShowUrl()
    {
        return '/project/' . $this->getId() . '/' . $this->getSlugName();
    }
    /**
     * @return string
     */
    public function getSlugName(): string
    {
        return $this->slugName;
    }

    /**
     * @param string $slugName
     */
    public function setSlugName(string $slugName)
    {
        $this->slugName = $slugName;
    }

    /**
     * @return string
     */
    public function getContributorsNbre()
    {
        return $this->contributorsNbre;
    }

    public function getContributorsNbreDisplay()
    {
        $count = $this->contributorsNbre;

        if($count === 0){
            $return = 'Aucun contributeur';

        }else {
            $return = $count . ' contributeur';
            if($count !== 1)
                $return .= 's';
        }

        return $return;
    }

    /**
     * @param int $contributorsNbre
     */
    public function setContributorsNbre(int $contributorsNbre)
    {
        $this->contributorsNbre = $contributorsNbre;
    }

    /**
     * @return mixed
     */
    public function getSkillListItems()
    {
        return $this->skillListItems;
    }

    public function setSkillListItems($skillListItems)
    {
        // Avoid existant skillListItems duplication
        $this->skillListItems->clear();

        // Loop and assign Entities to this Book
        foreach($skillListItems as $skill){
            if($skill instanceof ProjectList){
                $this->addSkillListItem($skill);
            }
        }
    }

    public function addSkillListItem(ProjectList $skill) {
        // Add BookHasMedia to array
        $this->skillListItems->add($skill);
        //Set this to bookHasMedia
        $skill->setProject($this);
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * @return string
     */
    public function getRawContent()
    {
        return $this->rawContent;
    }

    /**

src/Entity/Sonata/ProjectHasMedia.php
<?php
namespace App\Entity\Sonata;

use App\Entity\Project\Project;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class PostHasSong
 * @package App\Entity\Sonata
 *
 * @ORM\Entity()
 */
class ProjectHasMedia extends BaseHasMedia
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Project\Project", inversedBy="projectHasMedias", cascade={"persist"})
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     */
    private $project;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @return Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @param Project $project
     */
    public function setProject($project)
    {
        $this->project = $project;
    }

    public function isVideoMedia()
    {
        if($this->getMedia()->getProviderName() === 'sonata.media.provider.custom.image')
            return false;
        return true;
    }


    public function getUrlIfVideoMedia()
    {
        // Store parts of URL
        $media = $this->getMedia();
        $providerUrl = $media->getMetadataValue('provider_url');
        $urlAdd = '';
        $reference =  $media->getProviderReference();

        // Add url requirements if Dailymotion
        if(preg_match('%dailymotion%', $providerUrl)){
            $urlAdd = '/embed/video/';
        }

        // Concat & return
        return $providerUrl
            . $urlAdd
            . $reference;
    }

}

src/Controller/ProjectController.php
<?php
namespace App\Controller;

use App\Entity\Project\Project;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ProjectController extends Controller
{

    /**
     * @Route(
     *     "/projects",
     *     name="project_list"
     * )
     */
    public function listAction() {

        $em = $this->getDoctrine()->getManager();
        $projects = $em->getRepository(Project::class)
            ->findBy([], ['endDate' => 'DESC']);

        return $this->render(
            'project/list.html.twig',
            ['projects' => $projects]
        );

    }

    /**
     * @param $id
     * @param $slugName
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route(
     *     "/project/{id}/{slugName}",
     *     name="project_show",
     *     requirements={"slugName"="(.+|-)+"}
     * )
     */
    public function showAction($id, $slugName) {

        $em = $this->getDoctrine()->getManager();
        $project = $em->getRepository('App:Project\Project')
            ->findOneBy([
                'id' => $id,
                'slugName' => $slugName
            ]);

        if(is_null($project)) {
            throw new NotFoundHttpException('Aucune ressource ici...');
        }

        return $this->render(
            'project/show.html.twig',
            ['project' => $project]
        );

    }

    /**
     * @Route("/menu/projects", name="menu_projects")
     */
    public function getProjectsForMenus()
    {
        $projects = $this->getDoctrine()->getRepository(Project::class)
            ->findForMenu(['cat_name' => 'Game Design']);

        return $this->json($projects);
    }

}

templates/project/category.html.twig
{% extends 'project/list.html.twig' %}

{% block category_details %}

<section id="category-detail">
    <div class="category-detail-column">
        <div class="category-title">
            <span class="slash slash-right"></span>
            <h2>
                {{ cat.name }},
                <small>{{ projects.count }} projets</small>
            </h2>
        </div>
        <h4>Compétences mobilisées</h4>
        <ul id="skills-ul">
            {% for skill in cat.skillListItems %}
                <li>{{ skill.content }}</li>
            {% endfor %}
        </ul>
    </div>
    <div id="right-cat-col" class="category-detail-column">
        <div id="right-category-title" class="category-title">
            <h2>Dernier Projet
                <img src="/img/arrow-down.png" alt="Arrow down pictogram">
            </h2>
            <span class="slash slash-left"></span>
        </div>
        <ul>
            <li>
                <img src="/img/picto/note.png" alt="Bloc note pictogram">
                <a href="{{ projects.0.showUrl }}">
                    {{ projects.0.name }}
                </a>
            </li>
            <!-- High Concept -->
            <li>
                <img src="/img/picto/info.png" alt="Interrogation point pictogram">
                <span class="text-align-right">
                    {{ projects.0.highConceptType }} -
                    {{ projects.0.highConceptGender }} -
                    {{ projects.0.highConceptTarget }}
                </span>
            </li>
            <li>
                <img src="/img/picto/calendar.png" alt="Calendar pictogram">
                Terminé le {{ projects.0.endDate|date }}
            </li>
            <li>
                <img src="/img/picto/user.png" alt="User pictogram">
                {{ projects.0.contributorsNbreDisplay }}
            </li>
        </ul>
    </div>
</section>

    <hr>

{% endblock %}

{% block catlistscripts %}

    <!-- Toggle cat details -->
    <script type="application/javascript" src="/js/toggle-details.js"></script>
    <script type="application/javascript" src="/js/list-projects-toggle-cat.js"></script>

{% endblock %}

templates/project/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <!-- If project list by category -->
    {% block category_details %}{% endblock %}

    {% for project in projects %}

        <!-- Project item -->
        <section class="project-item-parent"
                 style="
                         background-image: url('{% path project.coverImage.media, 'reference' %}');
                         background-size: cover;
                         background-position: center;
                         ">
            <!-- Project left column -->
            <div class="list-column list-left-column">
                <span class="slash slash-right"></span>
                <span class="triangle-bg"></span>
                <!-- Title & Category -->
                <h2>
                    <a href="{{ project.showUrl }}"
                       title="Détails sur le projet {{ project.name }}">
                        {{ project.name }}</a>
                </h2>
            </div>

            <!-- Project left-column -->
            <div class="list-column list-right-column">
                <!-- Summary -->
                <p>{{ project.summary|raw }}</p>

                <!-- Project infos -->
                <ul>
                    <!-- High Concept -->
                    <li>
                        <img src="/img/picto/info.png" alt="Interrogation point pictogram">
                        {{ project.highConceptType }} -
                        {{ project.highConceptGender }} -
                        {{ project.highConceptTarget }}
                    </li>
                    <!-- Start date of Project -->
                    <li>
                        <img src="/img/picto/calendar.png" alt="Calendar pictogram">
                        Débuté le {{ project.initDate|date() }}
                    </li>

                    <!-- Duration of project -->
                    <li>
                        <img src="/img/picto/date-interval.png" alt="Date interval pictogram">
                        A duré {{ project.duration }}
                    </li>

                    <!-- Collaborators -->
                    <li>
                        <img src="/img/picto/user.png" alt="User pictogram">
                        {{ project.contributorsNbreDisplay }}
                    </li>
                </ul>

                <!-- Link to project show page -->
                <a href="{{ project.showUrl }}"
                   title="Détails sur le projet {{ project.name }}">
                    Lire {{ project.name }}</a>
            </div>
        </section>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block javascripts %}
    <!-- Toggle config -->
    <script type="text/javascript" src="/js/list-projects-toggle.js"></script>

    <!-- Slash config -->
    <script type="text/javascript" src="/js/slash-ajust.js"></script>
    <script type="text/javascript" src="/js/list-slash-config.js"></script>

    {% block catlistscripts %}{% endblock %}
{% endblock %}

templates/project/no-project.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>
        Aucun projet mis en ligne pour le moment
    </h1>
{% endblock %}

{% block javascripts %}
    <script>
        $("h1").css('text-align', 'center');
        $('footer').hide();
    </script>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <!-- Slick stylesheets -->
    <link rel="stylesheet" href="/vendor/slick/slick.css">
    <link rel="stylesheet" href="/vendor/slick/slick-theme.css">

    <!-- Fancybox stylesheet -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css">
{% endblock %}

{% block body %}
    <article id="project">
        <div class="project-row project-title">
            <span class="slash slash-right"></span>
            <h1 id="project-name">{{ project.name }}</h1>
        </div>
        <div class="project-row">
            <div class="project-column">
                <h4>Compétences mobilisées</h4>
                <ul id="skills-ul">
                    {% for skill in project.skillListItems %}
                        <li>{{ skill.content }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div id="project-details" class="project-column">
                <div id="project-details-title">
                    <h2>Détails
                        <img src="/img/arrow-down.png" alt="Arrow down pictogram">
                    </h2>
                </div>
                <ul id="project-infos">
                    <li>
                        <img src="/img/picto/info.png" alt="Interrogation point pictogram">
                        <span class="text-align-right">
                            {{ project.highConceptType }} -
                            {{ project.highConceptGender }} -
                            {{ project.highConceptTarget }}
                        </span>
                    </li>
                    <li>
                        <img src="/img/picto/calendar.png" alt="Calendar pictogram">
                        Terminé le {{ project.endDate|date() }}
                    </li>
                    <li>
                        <img src="/img/picto/date-interval.png" alt="Date interval pictogram">
                        Durée: {{ project.duration }}
                    </li>
                    <li>
                        <img src="/img/picto/user.png" alt="User pictogram">
                        {{ project.contributorsNbreDisplay }}
                    </li>
                </ul>
            </div>
        </div>

        <section id="project-gallery" class="project-row">
            <div class="slick-container">
                {% for phMedia in project.projectHasMedias %}
                    {% if phMedia.media is not null %}
                    {# Define media url to link #}
                    {% if phMedia.isVideoMedia %}
                        <a class="gallery-item-link" data-fancybox="gallery" href="{{ phMedia.urlIfVideoMedia }}">
                    {% else %}
                        <a class="gallery-item-link" data-fancybox="gallery" href="{% path phMedia.media, 'reference' %}">
                    {% endif %}
                        <img class="ui image gallery-img" src="{% path phMedia.media, 'big' %}" alt="">
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </section>

        <section id="project-content" class="project-row">
            {{ project.content|raw }}
        </section>
    </article>
{% endblock %}

{% block javascripts %}
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <!-- Slick js -->
    <script type="text/javascript" src="/vendor/slick/slick.min.js"></script>

    <!-- Fancybox JS -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js">
    </script>

    <!-- Config -->
    <script type="text/javascript" src="/js/show-project-gallery.js"></script>

    <!-- Slash config -->
    <script type="text/javascript" src="/js/slash-ajust.js"></script>
    <script type="text/javascript" src="/js/show-slash-config.js"></script>

    <!-- Toggle cat details -->
    <script type="application/javascript" src="/js/toggle-details.js"></script>
    <script type="application/javascript" src="/js/show-project-toggle-cat.js"></script>
{% endblock %}